[tool.poetry]
name = "news-blog"
version = "0.1.0"
description = ""
authors = ["vitalijtverskoj <vitalijtverskoj@gmail.com>"]
readme = "README.md"
packages = [{include = "news_blog"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
