"""empty message

Revision ID: 28474160c650
Revises: 758e5f60c981
Create Date: 2023-02-08 11:09:43.349414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28474160c650'
down_revision = '758e5f60c981'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_staff', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_staff')

    # ### end Alembic commands ###
