"""empty message

Revision ID: 758e5f60c981
Revises: 
Create Date: 2023-02-08 10:18:47.978658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '758e5f60c981'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
